apiVersion: apps/v1
kind: Deployment
metadata:
  name: mini-project-app-deployment
spec:
  replicas: 2 # ì•ˆì •ì„±ì„ ìœ„í•´ íŒŒë“œë¥¼ 2ê°œ ì‹¤í–‰í•©ë‹ˆë‹¤.
  selector:
    matchLabels:
      app: mini-project-app
  template:
    metadata:
      labels:
        app: mini-project-app
    spec:
      containers:
      - name: mini-project-app
        # ğŸš¨ ì¤‘ìš”: ArgoCDê°€ ì´ ì´ë¯¸ì§€ íƒœê·¸ë¥¼ ë‚˜ì¤‘ì— ìë™ìœ¼ë¡œ ë°”ê¿”ì¤„ ê²ƒì…ë‹ˆë‹¤.
        # ì²˜ìŒì—ëŠ” Docker Hubì— ìˆëŠ” íŠ¹ì • ë²„ì „(ì˜ˆ: 8)ìœ¼ë¡œ ì§€ì •í•©ë‹ˆë‹¤.
        image: minskko/mini-project-app:10
        ports:
        - containerPort: 8080 # app.pyì—ì„œ ì„¤ì •í•œ í¬íŠ¸
